language: java

sudo: required

matrix:
  fast_finish: true
  include:
#    - os: linux
#      jdk: openjdk16
#      sudo: required
#      env: DEPLOY=deploy_linux
    - os: osx
      osx_image: xcode9.2
      env: DEPLOY=deploy_osx

before_install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo apt-get update && sudo apt-get install oracle-java10-installer;
    elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update && brew install ant;
    fi

script:
  - git submodule update --quiet --init --recursive
  - cd MAVGCL && ant all
  - ant ${DEPLOY}

# On tags upload jar to Github
deploy:
  provider: releases
  api_key:
    secure: JWdIk6+Q9Kd1CjMJHqkGzxQ8jgnbNxO+ZfzbRXIkL1NQb9E0mtqZGf6MoBKgSa5jLcsx/v5bP4jIygyolnybCYgzK4WAeNJhE3mTkTFJLzj4RBx9xRJluLHMb54YG+QPzppefjcMRNmbyGQs8gq5hcCDlDPpBiGq5j3gGHIBZENqjz20PLOQVV643Ua8soAef5gIAdkVfAvdHz/RxowBto0K2Le2EDwBSXxtpyIuc8it8NQcRYDfX11+5a82HdoI3sV/NV0h8EcQGmfR7BCqqHqbCreIGHU5DByDTY9FmopsutWSuH+4LIsEzjo8xi6oJu/jQjFhXT8q4TOcEpj6GYE9XAhe/v9rMi9vAW8BWf0zPeC4tivm4wqzU2ySWDJshyes8oUvDKlrPfdF8t30S5JzXLOuhOO904EPbPejjWNT461FoWZTTo3wMOHds4bpvM4QHIR2lkFNdQzVSs7fIBtmzTuv7YEBBF68H1aDMrycksuf912JhdZ+peEIG/zXNYREssIt+dcXCr/MTBvEl3jYV59peMmC5YEuKArorfXKYYymjjLMHjbP7X8khZeM4CJZMsxVL4N8cO7BHg8uX5MQi1H+ZxNU1kM+2TA/Yhc8BaQFnIxEcikvtPk/0sTn5q5seDbtDivyNyK2e/mrahRdy8nE9aRLBMGExzDUvLQ=
  file_glob: true
  file:
    - "${TRAVIS_BUILD_DIR}/MAVGCL/dist/MAVGAnalysis*.jar"
    - "${TRAVIS_BUILD_DIR}/MAVGCL/dist/deploy/bundles/MAVGAnalysis*.dmg"
    - "${TRAVIS_BUILD_DIR}/MAVGCL/dist/deploy/bundles/mavganalysis*.deb"
  skip_cleanup: true
  on:
    tags: true
    repo: ecmnet/MAVGCL
